openapi: 3.0.3
info:
  title: PoJoker API
  description: API for the Digital Jester AI comedy application
  version: 1.0.0
  contact:
    email: punkouter26@gmail.com

servers:
  - url: /api
    description: Relative API path

paths:
  /jokes/fetch:
    get:
      operationId: fetchJoke
      summary: Fetch a random two-part joke from external API
      tags:
        - Jokes
      parameters:
        - name: safeMode
          in: query
          description: If true, excludes Dark and Rude joke categories
          required: false
          schema:
            type: boolean
            default: false
        - name: category
          in: query
          description: Filter by specific category
          required: false
          schema:
            type: string
            enum: [Programming, Misc, Dark, Pun, Spooky, Christmas]
      responses:
        '200':
          description: Successfully fetched a joke
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JokeDto'
        '503':
          description: External joke API unavailable
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

  /jokes/analyze:
    post:
      operationId: analyzeJoke
      summary: Send joke to AI for punchline prediction and analysis
      tags:
        - Jokes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzeJokeRequest'
      responses:
        '200':
          description: Successfully analyzed the joke
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JokePerformanceDto'
        '408':
          description: AI timeout (Jester is stumped)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JokePerformanceDto'
        '451':
          description: AI refused due to content policy (Speechless Jester)
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

  /leaderboard:
    get:
      operationId: getLeaderboard
      summary: Get top jokes by rating category
      tags:
        - Leaderboard
      parameters:
        - name: sortBy
          in: query
          description: Rating category to sort by
          required: true
          schema:
            type: string
            enum: [Cleverness, Rudeness, Complexity, Difficulty, Triumph]
        - name: category
          in: query
          description: Filter by joke category
          required: false
          schema:
            type: string
        - name: top
          in: query
          description: Number of results to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: Successfully retrieved leaderboard
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LeaderboardEntryDto'

  /diagnostics:
    get:
      operationId: getDiagnostics
      summary: Get health status of all external services
      tags:
        - Diagnostics
      responses:
        '200':
          description: All services healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiagnosticsDto'
        '503':
          description: One or more services unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiagnosticsDto'

components:
  schemas:
    JokeDto:
      type: object
      required:
        - id
        - setup
        - delivery
        - category
        - isSafe
      properties:
        id:
          type: string
          description: External API joke ID
          example: "232"
        setup:
          type: string
          maxLength: 500
          description: The joke premise/question
          example: "Why do programmers prefer dark mode?"
        delivery:
          type: string
          maxLength: 500
          description: The actual punchline
          example: "Because light attracts bugs."
        category:
          type: string
          enum: [Programming, Misc, Dark, Pun, Spooky, Christmas]
          example: "Programming"
        isSafe:
          type: boolean
          description: True if joke passes safe-mode filter

    AnalyzeJokeRequest:
      type: object
      required:
        - joke
        - sessionId
      properties:
        joke:
          $ref: '#/components/schemas/JokeDto'
        sessionId:
          type: string
          format: uuid
          description: Current performance session ID

    JokeRatingDto:
      type: object
      required:
        - cleverness
        - rudeness
        - complexity
        - difficulty
        - commentary
      properties:
        cleverness:
          type: integer
          minimum: 1
          maximum: 10
          description: Pun quality, logic twist rating
        rudeness:
          type: integer
          minimum: 1
          maximum: 10
          description: Insults, taboo subjects rating
        complexity:
          type: integer
          minimum: 1
          maximum: 10
          description: Domain knowledge required
        difficulty:
          type: integer
          minimum: 1
          maximum: 10
          description: How hard to predict the punchline
        commentary:
          type: string
          maxLength: 280
          description: Jester-persona witty remark

    JokePerformanceDto:
      type: object
      required:
        - id
        - joke
        - isAiTriumph
        - rating
        - performedAt
      properties:
        id:
          type: string
          format: uuid
        joke:
          $ref: '#/components/schemas/JokeDto'
        guessedPunchline:
          type: string
          nullable: true
          maxLength: 500
          description: AI's predicted punchline (null if stumped)
        isAiTriumph:
          type: boolean
          description: True if guess matches delivery
        rating:
          $ref: '#/components/schemas/JokeRatingDto'
        performedAt:
          type: string
          format: date-time

    LeaderboardEntryDto:
      type: object
      required:
        - jokeSetup
        - jokeDelivery
        - isTriumph
        - score
        - scoreType
        - performedAt
      properties:
        jokeSetup:
          type: string
        jokeDelivery:
          type: string
        aiGuess:
          type: string
          nullable: true
        isTriumph:
          type: boolean
        score:
          type: integer
          description: The rating value being sorted by
        scoreType:
          type: string
          enum: [Cleverness, Rudeness, Complexity, Difficulty, Triumph]
        performedAt:
          type: string
          format: date-time

    DiagnosticsDto:
      type: object
      required:
        - overallStatus
        - services
      properties:
        overallStatus:
          type: string
          enum: [Healthy, Degraded, Unhealthy]
        services:
          type: array
          items:
            $ref: '#/components/schemas/ServiceHealthDto'
        aiLatencyMs:
          type: integer
          nullable: true
          description: Last measured AI response time in milliseconds

    ServiceHealthDto:
      type: object
      required:
        - name
        - status
      properties:
        name:
          type: string
          example: "JokeAPI"
        status:
          type: string
          enum: [Healthy, Degraded, Unhealthy]
        message:
          type: string
          nullable: true
          description: Error message if unhealthy

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
          example: "The Jester Has Tripped!"
        status:
          type: integer
        detail:
          type: string
          example: "The Royal Scroll is missing!"
        instance:
          type: string
        jesterCode:
          type: string
          description: Exception type for debugging
